version: '3.8'

services:
  github-manager:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: github-login-manager
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET:-github-manager-secret-change-in-production}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-encryption-key-change-in-production}
      - TZ=Asia/Shanghai
    volumes:
      - github-data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - github-manager-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  github-manager-network:
    driver: bridge

volumes:
  github-data:
    driver: local