version: '3.8'

services:
  github-manager:
    build: .
    container_name: github-manager-python
    ports:
      - "10202:3000"  # 映射外部10202端口到内部3000端口
    environment:
      - PORT=3000
      - DATABASE_URL=sqlite:///./data/github_manager.db
      - ENCRYPTION_KEY=Z2l0aHViX21hbmFnZXJfc2VjcmV0X2tleV8zMmJ5dGU=
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - github-manager-network

networks:
  github-manager-network:
    driver: bridge

volumes:
  data: